name: Test Liquibase migrations

on:
  push:
    branches:
      - '**'  # matches every branch
      # - '!main'  # excludes main

  workflow_dispatch:  # run this workflow manually from the Actions tab

jobs:
  testLiquibaseMigrations:
    runs-on: ubuntu-18.04

    env:
      mssql_user: 'sa'
      mssql_pass: 'SqlSever123123'
      mssql_db: 'db'
      mssql_port: 1433
      change_log_file: 'changelog.xml'

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2017-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: ${{ env.mssql_pass }}
        ports:
          - 1433:1433

    steps:
      - name: Install SQL Server Client
        run: |
          sudo apt-get install curl
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          sudo apt-get update
          sudo apt-get install mssql-tools unixodbc-dev
          sudo ln -s /opt/mssql-tools/bin/sqlcmd /usr/bin/sqlcmd

      - name: Create database
        run: |
          sqlcmd -U ${mssql_user} -P ${mssql_pass} -Q "CREATE database ${mssql_db}"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Liquibase migrations
        uses: l-j/liquibase-github-action@main
        with:
          operation: 'updateTestingRollback'
          changeLogFile: ${{ env.change_log_file }}
          username: ${{ env.mssql_user }}
          password: ${{ env.mssql_pass }}
          url: 'jdbc:sqlserver://mssql:${{ env.mssql_port }};database=${{ env.mssql_db }};'
          classpath: '/liquibase/lib/mssql.jar'

      - name: Show Liquibase history
        uses: l-j/liquibase-github-action@main
        with:
          operation: 'history'
          changeLogFile: ${{ env.change_log_file }}
          username: ${{ env.mssql_user }}
          password: ${{ env.mssql_pass }}
          url: 'jdbc:sqlserver://mssql:${{ env.mssql_port }};database=${{ env.mssql_db }};'
          classpath: '/liquibase/lib/mssql.jar'
